### ISSUE TITLE
[Bug] If use other extension submit_post function

### ISSUE THREAD

**Issue by JV-KillBill** [Tatiana5/QuickReply#39]
[phpBB Debug] PHP Notice: in file [ROOT]/ext/tatiana5/quickreply/event/listener.php on line 478: Undefined index: topic_first_post_id
[phpBB Debug] PHP Notice: in file [ROOT]/ext/tatiana5/quickreply/event/listener.php on line 478: Undefined index: post_id

If we use a direct submit_post function, it is not required deliver this two variables.
PS: otherwise nice extension ;)

**Comment by lavigor** [comment]
> If we use a direct submit_post function, it is not required deliver this two variables.

Do you say that you wrote a custom extension that does not pass these parameters and you ask us to modify our extension to work in this case?

I think that you should instead make edits in your extension, because we currently rely on the parameters that are passed by the core. Otherwise we need to make additional database queries that we do not want.
This is not a bug of QuickReply.

**Comment by JV-KillBill** [comment]
Yes ;)

**Comment by JV-KillBill** [comment]
Hi!

phpBB no require use all parameters, if disabled QuickReply extension then no problem.

Why transported extra parameters, if it is not necessary for the proper functioning of phpBB?

quote “
Otherwise we need to make additional database queries that we do not want.

”

You extension no + query – you use example:

if (isset($data['topic_first_post_id']) && isset($data['post_id']))
